CRYPTOAUTHLIB_DIR := ../cryptoauthlib/lib

COMPONENT_SRCDIRS := $(CRYPTOAUTHLIB_DIR)/basic

COMPONENT_OBJS := $(CRYPTOAUTHLIB_DIR)/basic/atca_basic.o $(CRYPTOAUTHLIB_DIR)/basic/atca_basic_random.o

COMPONENT_ADD_INCLUDEDIRS := $(CRYPTOAUTHLIB_DIR)
